# Each new term in the Fib sequence i sgenerated by adding the previous two terms.
# By starting with 1 and 2, the first terms will be:

#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89

# By considering the terms in the Fib sequence whose values do not exceed four milion
# find the sum of the even-valued terms. 

# Essentially find the  sum of 2k numbers as long as num < 4 mil

def fib_gen():
    x = 1
    y = 1
    while True:
        yield y
        x, y = y, x + y

def sequence(func, LIMIT):
    sequence = []
    gen = func
    while True:
        check = next(gen)
        if check < LIMIT:
            sequence.append(check)
        else:
            break
    return sequence

def even(_list):
    new = [num for num in _list if num % 2 == 0]
    return new

LIMIT = 4 * 1000 * 1000

print (sum(even(sequence(fib_gen(), LIMIT))))
